name: Angular CI with NodeJS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone
      uses: actions/checkout@v3
    
    - name: Set up NodeJS 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
      
    - run: npm ci
    - run: npm run build
